spring:
  application:
    name: menu-service
  cache:
    type: redis
    redis:
      key-prefix: "menu::"
      time-to-live: 5m
      cache-null-values: false
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  servlet:
    context-path: /api/v1/menu
  port: 8081
