spring:
  config:
    import: "optional:configserver:http://localhost:8888"
  data:
    redis:
      host: localhost
      port: 6379
      client-type: lettuce
      connect-timeout: 2s
      timeout: 5s
      lettuce:
        pool:
          min-idle: 1
          max-idle: 5
          max-active: 20
